/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkbenchRouteImport } from './routes/workbench'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as GridRouteImport } from './routes/grid'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSavePromptRouteImport } from './routes/api/save-prompt'
import { Route as ApiPromptsRouteImport } from './routes/api/prompts'
import { Route as ApiPolishTemplateRouteImport } from './routes/api/polish-template'
import { Route as ApiPolishPromptRouteImport } from './routes/api/polish-prompt'
import { Route as ApiNextPromptRouteImport } from './routes/api/next-prompt'
import { Route as ApiNextRouteImport } from './routes/api/next'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as ApiCreateFromSvgRouteImport } from './routes/api/create-from-svg'
import { Route as ApiLibraryIndexRouteImport } from './routes/api/library/index'
import { Route as ApiDiscordExportIndexRouteImport } from './routes/api/discord-export/index'
import { Route as ApiLibraryUnhideRouteImport } from './routes/api/library/unhide'
import { Route as ApiLibraryItemRouteImport } from './routes/api/library/item'
import { Route as ApiLibraryHideRouteImport } from './routes/api/library/hide'
import { Route as ApiLibraryFileRouteImport } from './routes/api/library/file'
import { Route as ApiLibraryDeleteRouteImport } from './routes/api/library/delete'
import { Route as ApiDiscordExportPresetsRouteImport } from './routes/api/discord-export/presets'

const WorkbenchRoute = WorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const GridRoute = GridRouteImport.update({
  id: '/grid',
  path: '/grid',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSavePromptRoute = ApiSavePromptRouteImport.update({
  id: '/api/save-prompt',
  path: '/api/save-prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPromptsRoute = ApiPromptsRouteImport.update({
  id: '/api/prompts',
  path: '/api/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolishTemplateRoute = ApiPolishTemplateRouteImport.update({
  id: '/api/polish-template',
  path: '/api/polish-template',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolishPromptRoute = ApiPolishPromptRouteImport.update({
  id: '/api/polish-prompt',
  path: '/api/polish-prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNextPromptRoute = ApiNextPromptRouteImport.update({
  id: '/api/next-prompt',
  path: '/api/next-prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNextRoute = ApiNextRouteImport.update({
  id: '/api/next',
  path: '/api/next',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateFromSvgRoute = ApiCreateFromSvgRouteImport.update({
  id: '/api/create-from-svg',
  path: '/api/create-from-svg',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLibraryIndexRoute = ApiLibraryIndexRouteImport.update({
  id: '/api/library/',
  path: '/api/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscordExportIndexRoute = ApiDiscordExportIndexRouteImport.update({
  id: '/api/discord-export/',
  path: '/api/discord-export/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLibraryUnhideRoute = ApiLibraryUnhideRouteImport.update({
  id: '/api/library/unhide',
  path: '/api/library/unhide',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLibraryItemRoute = ApiLibraryItemRouteImport.update({
  id: '/api/library/item',
  path: '/api/library/item',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLibraryHideRoute = ApiLibraryHideRouteImport.update({
  id: '/api/library/hide',
  path: '/api/library/hide',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLibraryFileRoute = ApiLibraryFileRouteImport.update({
  id: '/api/library/file',
  path: '/api/library/file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLibraryDeleteRoute = ApiLibraryDeleteRouteImport.update({
  id: '/api/library/delete',
  path: '/api/library/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscordExportPresetsRoute = ApiDiscordExportPresetsRouteImport.update({
  id: '/api/discord-export/presets',
  path: '/api/discord-export/presets',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/generate': typeof GenerateRoute
  '/grid': typeof GridRoute
  '/library': typeof LibraryRoute
  '/workbench': typeof WorkbenchRoute
  '/api/create-from-svg': typeof ApiCreateFromSvgRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/next': typeof ApiNextRoute
  '/api/next-prompt': typeof ApiNextPromptRoute
  '/api/polish-prompt': typeof ApiPolishPromptRoute
  '/api/polish-template': typeof ApiPolishTemplateRoute
  '/api/prompts': typeof ApiPromptsRoute
  '/api/save-prompt': typeof ApiSavePromptRoute
  '/api/discord-export/presets': typeof ApiDiscordExportPresetsRoute
  '/api/library/delete': typeof ApiLibraryDeleteRoute
  '/api/library/file': typeof ApiLibraryFileRoute
  '/api/library/hide': typeof ApiLibraryHideRoute
  '/api/library/item': typeof ApiLibraryItemRoute
  '/api/library/unhide': typeof ApiLibraryUnhideRoute
  '/api/discord-export/': typeof ApiDiscordExportIndexRoute
  '/api/library/': typeof ApiLibraryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/generate': typeof GenerateRoute
  '/grid': typeof GridRoute
  '/library': typeof LibraryRoute
  '/workbench': typeof WorkbenchRoute
  '/api/create-from-svg': typeof ApiCreateFromSvgRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/next': typeof ApiNextRoute
  '/api/next-prompt': typeof ApiNextPromptRoute
  '/api/polish-prompt': typeof ApiPolishPromptRoute
  '/api/polish-template': typeof ApiPolishTemplateRoute
  '/api/prompts': typeof ApiPromptsRoute
  '/api/save-prompt': typeof ApiSavePromptRoute
  '/api/discord-export/presets': typeof ApiDiscordExportPresetsRoute
  '/api/library/delete': typeof ApiLibraryDeleteRoute
  '/api/library/file': typeof ApiLibraryFileRoute
  '/api/library/hide': typeof ApiLibraryHideRoute
  '/api/library/item': typeof ApiLibraryItemRoute
  '/api/library/unhide': typeof ApiLibraryUnhideRoute
  '/api/discord-export': typeof ApiDiscordExportIndexRoute
  '/api/library': typeof ApiLibraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/generate': typeof GenerateRoute
  '/grid': typeof GridRoute
  '/library': typeof LibraryRoute
  '/workbench': typeof WorkbenchRoute
  '/api/create-from-svg': typeof ApiCreateFromSvgRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/next': typeof ApiNextRoute
  '/api/next-prompt': typeof ApiNextPromptRoute
  '/api/polish-prompt': typeof ApiPolishPromptRoute
  '/api/polish-template': typeof ApiPolishTemplateRoute
  '/api/prompts': typeof ApiPromptsRoute
  '/api/save-prompt': typeof ApiSavePromptRoute
  '/api/discord-export/presets': typeof ApiDiscordExportPresetsRoute
  '/api/library/delete': typeof ApiLibraryDeleteRoute
  '/api/library/file': typeof ApiLibraryFileRoute
  '/api/library/hide': typeof ApiLibraryHideRoute
  '/api/library/item': typeof ApiLibraryItemRoute
  '/api/library/unhide': typeof ApiLibraryUnhideRoute
  '/api/discord-export/': typeof ApiDiscordExportIndexRoute
  '/api/library/': typeof ApiLibraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/generate'
    | '/grid'
    | '/library'
    | '/workbench'
    | '/api/create-from-svg'
    | '/api/generate'
    | '/api/next'
    | '/api/next-prompt'
    | '/api/polish-prompt'
    | '/api/polish-template'
    | '/api/prompts'
    | '/api/save-prompt'
    | '/api/discord-export/presets'
    | '/api/library/delete'
    | '/api/library/file'
    | '/api/library/hide'
    | '/api/library/item'
    | '/api/library/unhide'
    | '/api/discord-export/'
    | '/api/library/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/generate'
    | '/grid'
    | '/library'
    | '/workbench'
    | '/api/create-from-svg'
    | '/api/generate'
    | '/api/next'
    | '/api/next-prompt'
    | '/api/polish-prompt'
    | '/api/polish-template'
    | '/api/prompts'
    | '/api/save-prompt'
    | '/api/discord-export/presets'
    | '/api/library/delete'
    | '/api/library/file'
    | '/api/library/hide'
    | '/api/library/item'
    | '/api/library/unhide'
    | '/api/discord-export'
    | '/api/library'
  id:
    | '__root__'
    | '/'
    | '/generate'
    | '/grid'
    | '/library'
    | '/workbench'
    | '/api/create-from-svg'
    | '/api/generate'
    | '/api/next'
    | '/api/next-prompt'
    | '/api/polish-prompt'
    | '/api/polish-template'
    | '/api/prompts'
    | '/api/save-prompt'
    | '/api/discord-export/presets'
    | '/api/library/delete'
    | '/api/library/file'
    | '/api/library/hide'
    | '/api/library/item'
    | '/api/library/unhide'
    | '/api/discord-export/'
    | '/api/library/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenerateRoute: typeof GenerateRoute
  GridRoute: typeof GridRoute
  LibraryRoute: typeof LibraryRoute
  WorkbenchRoute: typeof WorkbenchRoute
  ApiCreateFromSvgRoute: typeof ApiCreateFromSvgRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiNextRoute: typeof ApiNextRoute
  ApiNextPromptRoute: typeof ApiNextPromptRoute
  ApiPolishPromptRoute: typeof ApiPolishPromptRoute
  ApiPolishTemplateRoute: typeof ApiPolishTemplateRoute
  ApiPromptsRoute: typeof ApiPromptsRoute
  ApiSavePromptRoute: typeof ApiSavePromptRoute
  ApiDiscordExportPresetsRoute: typeof ApiDiscordExportPresetsRoute
  ApiLibraryDeleteRoute: typeof ApiLibraryDeleteRoute
  ApiLibraryFileRoute: typeof ApiLibraryFileRoute
  ApiLibraryHideRoute: typeof ApiLibraryHideRoute
  ApiLibraryItemRoute: typeof ApiLibraryItemRoute
  ApiLibraryUnhideRoute: typeof ApiLibraryUnhideRoute
  ApiDiscordExportIndexRoute: typeof ApiDiscordExportIndexRoute
  ApiLibraryIndexRoute: typeof ApiLibraryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workbench': {
      id: '/workbench'
      path: '/workbench'
      fullPath: '/workbench'
      preLoaderRoute: typeof WorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grid': {
      id: '/grid'
      path: '/grid'
      fullPath: '/grid'
      preLoaderRoute: typeof GridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/save-prompt': {
      id: '/api/save-prompt'
      path: '/api/save-prompt'
      fullPath: '/api/save-prompt'
      preLoaderRoute: typeof ApiSavePromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prompts': {
      id: '/api/prompts'
      path: '/api/prompts'
      fullPath: '/api/prompts'
      preLoaderRoute: typeof ApiPromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polish-template': {
      id: '/api/polish-template'
      path: '/api/polish-template'
      fullPath: '/api/polish-template'
      preLoaderRoute: typeof ApiPolishTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polish-prompt': {
      id: '/api/polish-prompt'
      path: '/api/polish-prompt'
      fullPath: '/api/polish-prompt'
      preLoaderRoute: typeof ApiPolishPromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/next-prompt': {
      id: '/api/next-prompt'
      path: '/api/next-prompt'
      fullPath: '/api/next-prompt'
      preLoaderRoute: typeof ApiNextPromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/next': {
      id: '/api/next'
      path: '/api/next'
      fullPath: '/api/next'
      preLoaderRoute: typeof ApiNextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-from-svg': {
      id: '/api/create-from-svg'
      path: '/api/create-from-svg'
      fullPath: '/api/create-from-svg'
      preLoaderRoute: typeof ApiCreateFromSvgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/library/': {
      id: '/api/library/'
      path: '/api/library'
      fullPath: '/api/library/'
      preLoaderRoute: typeof ApiLibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discord-export/': {
      id: '/api/discord-export/'
      path: '/api/discord-export'
      fullPath: '/api/discord-export/'
      preLoaderRoute: typeof ApiDiscordExportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/library/unhide': {
      id: '/api/library/unhide'
      path: '/api/library/unhide'
      fullPath: '/api/library/unhide'
      preLoaderRoute: typeof ApiLibraryUnhideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/library/item': {
      id: '/api/library/item'
      path: '/api/library/item'
      fullPath: '/api/library/item'
      preLoaderRoute: typeof ApiLibraryItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/library/hide': {
      id: '/api/library/hide'
      path: '/api/library/hide'
      fullPath: '/api/library/hide'
      preLoaderRoute: typeof ApiLibraryHideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/library/file': {
      id: '/api/library/file'
      path: '/api/library/file'
      fullPath: '/api/library/file'
      preLoaderRoute: typeof ApiLibraryFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/library/delete': {
      id: '/api/library/delete'
      path: '/api/library/delete'
      fullPath: '/api/library/delete'
      preLoaderRoute: typeof ApiLibraryDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discord-export/presets': {
      id: '/api/discord-export/presets'
      path: '/api/discord-export/presets'
      fullPath: '/api/discord-export/presets'
      preLoaderRoute: typeof ApiDiscordExportPresetsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenerateRoute: GenerateRoute,
  GridRoute: GridRoute,
  LibraryRoute: LibraryRoute,
  WorkbenchRoute: WorkbenchRoute,
  ApiCreateFromSvgRoute: ApiCreateFromSvgRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiNextRoute: ApiNextRoute,
  ApiNextPromptRoute: ApiNextPromptRoute,
  ApiPolishPromptRoute: ApiPolishPromptRoute,
  ApiPolishTemplateRoute: ApiPolishTemplateRoute,
  ApiPromptsRoute: ApiPromptsRoute,
  ApiSavePromptRoute: ApiSavePromptRoute,
  ApiDiscordExportPresetsRoute: ApiDiscordExportPresetsRoute,
  ApiLibraryDeleteRoute: ApiLibraryDeleteRoute,
  ApiLibraryFileRoute: ApiLibraryFileRoute,
  ApiLibraryHideRoute: ApiLibraryHideRoute,
  ApiLibraryItemRoute: ApiLibraryItemRoute,
  ApiLibraryUnhideRoute: ApiLibraryUnhideRoute,
  ApiDiscordExportIndexRoute: ApiDiscordExportIndexRoute,
  ApiLibraryIndexRoute: ApiLibraryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
